title: "Kharbozeh News"
baseurl: "/kharbozeh"
url: "https://secneuqecnoc-netizen.github.io"

# تنظیمات نمایش
markdown: kramdown
permalink: pretty

# پلاگین‌ها (فقط موارد مجاز گیت‌هاب)
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# تنظیمات صفحه بندی
paginate: 5
paginate_path: "/page/:num"

# حذف فایل‌های اضافی از پردازش
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
